### PR TITLE
Remove NetworkManager

### PR DESCRIPTION
**Pull request by Sorbog**
### Description

Move removing NetworkManager to kickstart

### CODE REVIEW

**Comment by tas50** [comment]
CC: @cheeseplus I know you've gone back and forth on the networkmanager mess for a while

**Comment by cheeseplus** [comment]
This seems to be moving this to kickstart, which if it works, I'm all for since the net effect will be the same. I'm +1 assuming it doesn't uncover some weird edge case.

**Comment by aequitas** [comment]
@Sorbog I noticed (in both approaches) that removing NetworkManager leads to an increased startup time for the VM of around 30 seconds because during boot it times out on the systemd unit `NetworkManager-wait-online.service`. Maybe this could also be removed/disabled?

**Comment by tas50** [comment]
I'm going to close this out at this point since we never heard back about the increased startup time and the change now conflicts with the ks files for 7.

**Pull request closed without merging**
