### PR TITLE
Added Ubuntu 16.10

### PR DESCRIPTION
**Pull request by rickard-von-essen**
_amd64_ tested on:
- Parallels Desktop 12 for Mac Pro Ed. 12.0.2
- VMware Fusion 7.1.3
- VirtualBox 5.1.6

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
The regression from 15.10 reported in https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1505839 seems to be fixed now.

**Comment by rickard-von-essen** [comment]
I reused `preseed-15.10.cfg` without copying it.

**Comment by tas50** [comment]
The failure here is on SLES and it's been fixed on master since then. This should be good to go.

**Comment by cheeseplus** [comment]
lgtm

**Pull request merged**
