### PR TITLE
Add FreeBSD 10.3

### PR DESCRIPTION
**Pull request by tas50**
Also move the install script for FreeBSD 10 into a major version directory

### CODE REVIEW

**Comment by cheeseplus** [comment]
+1

**Comment by rickard-von-essen** [comment]
It's now released. 👍

**Comment by tas50** [comment]
The build on vbox completes without issues on my local box and then fails, with a problem that I think is related to my local box.  This *should* be good to go though.

**Comment by cheeseplus** [comment]
+1

**Pull request merged**
