### PR TITLE
added Debian 12

### PR DESCRIPTION
**Pull request by mmguero**
## Description
With the release of Debian 12 (stable), added Debian 12.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
Debian 10 LTS doesn't end until next year

**Comment by mmguero** [comment]
ah, i'll put the debian 10 back in then. I was assuming the project was doing stable and oldstable.

**Comment by Stromweld** [comment]
can you also add to the plugins list to fix the provisioner error: 
```
chef = {
  version = ">= 1.0.0"
  source  = "github.com/hashicorp/chef"
}
```

**Comment by mmguero** [comment]
Okay, restored debian-10 and added the plugin, let me know if you'd like me to change anything else

**Comment by Stromweld** [comment]
looks like you missed the DCO sign off on your last commit

**Comment by Stromweld** [comment]
Looks good. I have a couple of things to fix the pipelines then should see builds working better again.

**Review by Stromweld — APPROVED** [review]
LGTM

**Pull request merged**
