### PR TITLE
preliminary debian 8.1 templates

### PR DESCRIPTION
**Pull request by rmoriz**
Templates for #379

beware, not tested!

### CODE REVIEW

**Comment by fnichol** [comment]
@rmoriz Thanks! I'll give these a test through, cc @cheeseplus

**Comment by cheeseplus** [comment]
I'll try to test these today too - I was working on this yesterday but Virtualbox kernel panicked the first time I tested :(

**Comment by cheeseplus** [comment]
Not off to a good start, looks like the URL provided isn't going to work for the ISO

```
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://cdimage.debian.org/cdimage/archive/8.1.0/amd64/iso-cd/debian-8.1.0-amd64-CD-1.iso
    virtualbox-iso: Error downloading: HTTP error '404'! Remote side responded:
    virtualbox-iso: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    virtualbox-iso: <html><head>
    virtualbox-iso: <title>404 Not Found</title>
    virtualbox-iso: </head><body>
    virtualbox-iso: <h1>Not Found</h1>
    virtualbox-iso: <p>The requested URL /cdimage/archive/8.1.0/amd64/iso-cd/debian-8.1.0-amd64-CD-1.iso was not found on this server.</p>
    virtualbox-iso: <hr>
    virtualbox-iso: <address>Apache/2.4.12 (Unix) Server at cdimage.debian.org Port 80</address>
    virtualbox-iso: </body></html>
    virtualbox-iso:
```

**Comment by rmoriz** [comment]
Sorry, copy + paste fail. 8.1.0 is not on archive as it is the current release. We'll have to change the file once 8.1.x or 8.2.x will be released.

**Comment by cheeseplus** [comment]
Nice, was just about to comment and you've already fixed it (I made the edit locally and it's running right now)

**Comment by cheeseplus** [comment]
Tested with the git cookbook and test-kitchen
- [X] amd64
- [  ] i386

**Comment by cheeseplus** [comment]
I have completed all the tests and everything checks out. I'll push these to S3 and test again just to make sure everything works but since this is a _new_ platform I'm not terribly worried.

**Comment by fnichol** [comment]
Nice, thanks @cheeseplus and @rmoriz!

**Pull request merged**
