### PR TITLE
Possible increase performance for some Virtualbox builds

### PR DESCRIPTION
**Pull request by rubisher**
## Description

Some virtualbox are build with 'SATA Controler' with host I/O cache disable by default.
This reduce the performance of the VM.
Fortunately it is possible put this switch on (which also increase the speed of the VM.)
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by Stromweld** [comment]
Can you add the DCO sign off to your commit.

**Comment by rubisher** [comment]
> Can you add the DCO sign off to your commit.

As it is my very first pull request , can you check if that is acceptable now?
Thx for patience, Rudy

**Comment by rubisher** [comment]
Hello,
It seems that I even find a more elegant way for this Virtualbox alternatives:
1. adding some alternate soure (and some related var):
```
diff --git a/packer_templates/pkr-variables.pkr.hcl b/packer_templates/pkr-variables.pkr.hcl
index 88d1a7b..5452b17 100644
--- a/packer_templates/pkr-variables.pkr.hcl
+++ b/packer_templates/pkr-variables.pkr.hcl
@@ -41,6 +41,9 @@ variable "sources_enabled" {
     "source.hyperv-iso.vm",
     "source.parallels-iso.vm",
     "source.qemu.vm",
+    "source.virtualbox-iso.vm-vb7",
+    "source.virtualbox-iso.vm-vb7-efi",
+    "source.virtualbox-iso.vm-vb7-efi-AHCI",
     "source.virtualbox-iso.vm",
     "source.vmware-iso.vm",
   ]
@@ -156,6 +160,44 @@ variable "vboxmanage" {
     ]
   ]
 }
+variable "vboxmanage-vb7" {
+  type = list(list(string))
+  default = [
+    [
+      "modifyvm", "{{.Name}}",
+      "--audio", "none",
+      "--nat-localhostreachable1", "on",
+    ]
+  ]
+}
+variable "vboxmanage-vb7-efi" {
+  type = list(list(string))
+  default = [
+    [
+      "modifyvm", "{{.Name}}",
+      "--audio", "none",
+      "--nat-localhostreachable1", "on",
+      "--firmware", "efi",
+    ]
+  ]
+}
+variable "vboxmanage-vb7-efi-AHCI" {
+  type = list(list(string))
+  default = [
+    [
+      "modifyvm", "{{.Name}}",
+      "--audio", "none",
+      "--nat-localhostreachable1", "on",
+      "--firmware", "efi",
+    ]
+    ,
+    [
+      "storagectl", "{{.Name}}",
+      "--name", "SATA Controller",
+      "--hostiocache", "on",
+    ]
+  ]
+}
 variable "virtualbox_version_file" {
   type    = string
   default = ".vbox_version"
```
2. define this new sources (just one sample):
```
diff --git a/packer_templates/pkr-sources.pkr.hcl b/packer_templates/pkr-sources.pkr.hcl
index c57e84a..98c437c 100644
--- a/packer_templates/pkr-sources.pkr.hcl
+++ b/packer_templates/pkr-sources.pkr.hcl
@@ -232,6 +232,44 @@ source "virtualbox-iso" "vm" {
   winrm_username            = var.winrm_username
   vm_name                   = local.vm_name
 }
+#===<>===#
+source "virtualbox-iso" "vm-vb7" {}
+source "virtualbox-iso" "vm-vb7-efi" {}
+source "virtualbox-iso" "vm-vb7-efi-AHCI" {
+  gfx_controller            = local.vbox_gfx_controller
+  gfx_vram_size             = local.vbox_gfx_vram_size
+  guest_additions_path      = var.vbox_guest_additions_path
+  guest_additions_mode      = local.vbox_guest_additions_mode
+  guest_additions_interface = var.vbox_guest_additions_interface
+  guest_os_type             = var.vbox_guest_os_type
+  hard_drive_interface      = var.vbox_hard_drive_interface
+  iso_interface             = var.vbox_iso_interface
+  vboxmanage                = var.vboxmanage-vb7-efi-AHCI
+  virtualbox_version_file   = var.virtualbox_version_file
+  boot_command              = var.boot_command
+  boot_wait                 = local.boot_wait
+  cpus                      = var.cpus
+  communicator              = local.communicator
+  disk_size                 = var.disk_size
+  floppy_files              = local.floppy_files
+  headless                  = var.headless
+  http_directory            = local.http_directory
+  iso_checksum              = var.iso_checksum
+  iso_url                   = var.iso_url
+  memory                    = local.memory
+  output_directory          = "${local.output_directory}-virtualbox"
+  shutdown_command          = local.shutdown_command
+  shutdown_timeout          = var.shutdown_timeout
+  ssh_password              = var.ssh_password
+  ssh_port                  = var.ssh_port
+  ssh_timeout               = var.ssh_timeout
+  ssh_username              = var.ssh_username
+  winrm_password            = var.winrm_password
+  winrm_timeout             = var.winrm_timeout
+  winrm_username            = var.winrm_username
+  vm_name                   = local.vm_name
+}
+#===<>===#
 source "virtualbox-ovf" "amazonlinux" {
   guest_additions_path    = var.vbox_guest_additions_path
   source_path             = local.vbox_source
```
such that I can build a -only=virtualbox-iso.vm-vb7-efi-AHCI 

(I just don't have the 'kitchen' environment to test all this chnages :()

What is your opinion?

Thx in advance, Rudy

**Comment by Stromweld** [comment]
I like the ideas, since vboxmanage is a variable it can simply be updated by adding the override to the default in pkrvars.hcl file. You can also add multiple pkrvars.hcl files to a command by adding another -var-file= parameter and have a pkrvars file then with just the override to add efi. Otherwise I think the better route would be to add the firmware option, https://developer.hashicorp.com/packer/plugins/builders/virtualbox/iso#firmware, to the virtualbox-iso.vm source and assign it to a variable with a default "bios". instead of doing it through vboxmanage. then the same thing can be done with custom pkrvars files that simply override that one option to enable efi or not for a build.

**Comment by rubisher** [comment]
> I like the ideas, since vboxmanage is a variable it can simply be updated by adding the override to the default in pkrvars.hcl file. You can also add multiple pkrvars.hcl files to a command by adding another -var-file= parameter and have a pkrvars file then with just the override to add efi. Otherwise I think the better route would be to add the firmware option, https://developer.hashicorp.com/packer/plugins/builders/virtualbox/iso#firmware, to the virtualbox-iso.vm source and assign it to a variable with a default "bios". instead of doing it through vboxmanage. then the same thing can be done with custom pkrvars files that simply override that one option to enable efi or not for a build.

Thx a lot for advises, I will investigate by leaning hcl in deepest details ;)
Rudy

**Pull request closed without merging**
