### PR TITLE
Add support for OpenSUSE Leap 42.1 - x86_64

### LINKED ISSUE #504: OpenSUSE Leap (and Tumbleweed)
There are two new types of OpenSUSE, Leap and Tumbleweed.

- Leap is OpenSUSE's new release which is the upstream of SLES, much like Fedora is for RHEL.
- Tumbleweed Is a rolling release with all package that passed OpenSUSE's QA. This might prove a challenge to implement Ina good way coping with the constant updates.

Is Chef interested in adding Leap and possible Tumbleweed? If so I can start working on two PR's.

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Fixes #504

### CODE REVIEW

**Comment by spuranam** [comment]
Please take look at pull request [538](https://github.com/chef/bento/pull/538), that just push. I made few changes to your original contribution, so it looks more like SLES 12 SP1 image i built. These changes are quite minor but enable me to have common sysadmin tools like yast, firewall etc. which makes it easy to test several chef products.

**Comment by cheeseplus** [comment]
@spuranam the purposes of the templates is to be as generic/agnostic as possible so that you can further customize with config mgmt or other things. I'd defer to @rickard-von-essen as to whether these changes are needed for a base OpenSUSE.

**Comment by spuranam** [comment]
@cheeseplus i was able to make all the changes i wanted via chef client run, hence my changes to this pull request are not required. However i would appreciate if this pull request could be merged. Also is there any interest in SLES 12 SP1 templates, if so i would send in a pull request.

@rickard-von-essen  thanks for your time.

**Comment by gsaslis** [comment]
:+1: on having this merged in! 
Would be cool to have Leap support here.

**Pull request merged**
