### PR TITLE
Add centos 7.1

### PR DESCRIPTION
**Pull request by kramvan1**

### CODE REVIEW

**Comment by bdwyertech** [comment]
Are y'all trying to maintain the eth0 interface naming convention, or are we going with the new method?  
Also, NetworkManager makes multiple interfaces with Vagrant a real PITA, since it increments the route metric, making all outbound traffic always flow through the default NAT'd interface.

**Comment by irvingpop** [comment]
:thumbsup:  Tested this out,  works correctly.   Networking is the same as the centos-7.0 bento box, so no issues for me.

**Comment by juliandunn** [comment]
@bdwyertech our general philosophy in Bento is to leave the defaults alone, so I guess that implies "new method".

**Comment by juliandunn** [comment]
Merged in 757efdd8fc9a09a83a2730e135fb01247f27d4b2. Thanks!

**Pull request closed without merging**
