### PR TITLE
Don't install src while creating box

### PR DESCRIPTION
**Pull request by lwhsu**
This speeds up box creation a lot.  The box creation is using pkg(1)
to install software so doesn't need source files.  It doesn't make much
sense installing all the source files and then deleting them during
cleanup stage.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Have you verified that this is not needed to install VMware tools?

**Comment by lwhsu** [comment]
Ahhh... I thought it uses `emulators/open-vm-tools`.  I'll check if it is possible to switch.

**Comment by rickard-von-essen** [comment]
That would be great!

**Comment by lwhsu** [comment]
Ref: #957

**Pull request merged**
