### PR TITLE
Adding OmniOS r151014

### PR DESCRIPTION
**Pull request by cheeseplus**
More Illumos for the Illumos Gods

### CODE REVIEW

**Comment by yzl** [comment]
:+1:

**Comment by fd1e4020** [comment]
Has there been an upstream refresh of the ISO image? The published checksum doesn't match the json's.

**Comment by rickard-von-essen** [comment]
This seems to happen from time to time, see #470

**Comment by cheeseplus** [comment]
Yea, the OmniOS folks keep the same image name but change the ISO which is incredibly annoying and a less than ideal release engineering practice :/

**Pull request merged**
