### PR TITLE
Updated to OpenSUSE Leap 42.2

### PR DESCRIPTION
**Pull request by rickard-von-essen**
- Had to reduce the number of packages that is cleaned up for OpenSUSE 42.2.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
Done

**Comment by cheeseplus** [comment]
Any reason you chose en_us over en_us.utf8? I ask as we just shifted Debian platforms to en_us.utf8 for things like Postgres.

**Comment by rickard-von-essen** [comment]
> Any reason you chose en_us over en_us.utf8?

The installer fails when using `en_us.UTF-8` and gave a list of supported languages. I don't know why this changed, I guess previously it have failed and the installer defaulted to `en_US` or something.

[A quick googling gave me this](http://doc.opensuse.org/documentation/leap/reference/single-html/book.opensuse.reference/#sec.suse.l10n.examples):

    LANG=en_US.UTF-8

    This is the default setting if American English is selected during installation. If you selected another language, that language is enabled but still with UTF-8 as the character encoding.

**Comment by cheeseplus** [comment]
Weird but that answer works for me!

**Pull request merged**
