### PR TITLE
Match any kernel version in debian purge command

### PR DESCRIPTION
**Pull request by upekkha**
The `cleanup_debian.sh` script was only removing kernel versions starting with `[234]` and thus not matching the current kernel versions 5 or 6. This PR suggests to match any version `[1-9]`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by Stromweld** [comment]
Have you tested this change? My only concern is that it'll remove all linux-image packages even for the current kernel.

**Comment by upekkha** [comment]
I locally tested with Debian 10, 11 and upcoming 12. The currently running kernel is anyway excluded by the `grep -v "$(uname -r)"` on the next line.

**Comment by Stromweld** [comment]
gotcha I see it now. makes sense thanks.

**Review by Stromweld — APPROVED** [review]
LGTM

**Pull request merged**
