### PR TITLE
Ubuntu

### PR DESCRIPTION
**Pull request by githubfoam**
mirror_directory": "16.04.3" <-> mirror_directory": "16.04.4"
http://releases.ubuntu.com/releases/

### CODE REVIEW

**Comment by cheeseplus** [comment]
Can we can the scientific linux changes as a separate PR? This is doing too much in one PR.

**Comment by githubfoam** [comment]
seperate PR? never done before.

**Comment by cheeseplus** [comment]
You have two PRs - https://github.com/chef/bento/pull/1048 and this one which includes all changes in #1048. We don't need the changes in both PRs and typically you want to keep changes/PRs/features scoped to the specific thing they are fixing.

**Comment by githubfoam** [comment]
I am closing this and leaving other one.Is it ok?

**Pull request closed without merging**
