### PR TITLE
Retire deprecated boxes

### PR DESCRIPTION
**Pull request by tas50**
Retire:

Debian 6
Fedora 21
Ubuntu 10.04
Ubuntu 15.04

Also fix the table to include i386 FreeBSD links

### CODE REVIEW

**Comment by cheeseplus** [comment]
Something I've meant to do for a bit is not to delete these but move to a deprecated or archive folder - happy to accept the PR but would live to keep the templates, just move label them accordingly

**Comment by tas50** [comment]
Easy enough. I'll move them tomorrow

**Comment by tas50** [comment]
I assume we're ok with not updating the paths to the scripts still work?  Just moving them off to something like "archive" and being done with it.

**Comment by cheeseplus** [comment]
I'd like to write something that can bulk update the paths or make the bento binary do something with it - not critical and we can do as a second pass.

**Comment by tas50** [comment]
Closing this out since we need a better approach

**Pull request closed without merging**
