### PR TITLE
Add support for macOS Sierra 10.12

### PR DESCRIPTION
**Pull request by legal90**
The template has been copied from `macosx-10.11.json` .I've verified it with `parallels-iso` builder - it works fine.

But I'm not sure - should I change `guest_os_type` value for `vmware-iso` and `virtualbox` builders or not. I'd appreciate if someone verifies the template with these builders.

### CODE REVIEW

**Comment by cheeseplus** [comment]
Trying to test this today - got stuck on softwareupdate earlier but hopefully that was just transient.

**Comment by legal90** [comment]
Yes, `softwareupdate` could take a while because of updates installation. Have you managed to repeat the build?

**Comment by cheeseplus** [comment]
@legal90 it never seems to complete at that stage (I've only tried with Parallels builder) and I'm not sure how long I should be waiting before calling it hung - are you giving it tons of resources or anything? what do your build times look like?

**Comment by legal90** [comment]
No, I use a regular MacBook Air, early 2014. 
But yeah, now I can confirm that the build hangs for more than 1h on this step:
```
==> parallels-iso: Provisioning with shell script: scripts/macosx/update.sh
    parallels-iso: + softwareupdate --install --all
    parallels-iso: Software Update Tool
    parallels-iso: Copyright 2002-2015 Apple Inc.
    parallels-iso:
    parallels-iso: Finding available software
    parallels-iso:
    parallels-iso: Downloading macOS Sierra Update
    parallels-iso: Downloading iTunes

```
and there is still no progress. Probably, it makes sense to try to rebuild the source .dmg and remove all redundant stuff like iTunes from there...

**Comment by kameghamegha** [comment]
I'm testing some more right now, but I was able to get the softwareupdate segment working when I made these changes to the updates script:

```
softwareupdate --background --force --verbose;
softwareupdate --install --all --force --verbose;
```

Not sure the first line is required (I have yet to test without it), but it seems to work with the --force and --verbose options being added.

**Comment by cheeseplus** [comment]
Superseded by #715 but as always the contributions are welcome @legal90

**Pull request closed without merging**
