### PR TITLE
Add support for Ubuntu 22.04 LTS (Jammy)

### PR DESCRIPTION
**Pull request by matuskosut**
## Description

add ubuntu 22.04 jammy template

## Related Issue

https://github.com/chef/bento/issues/1405

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by svpernova09** [comment]
Successfully able to build here. Thanks!

Build Details:

macOS: 12.3.1
Packer: 1.8.0
VirtualBox: 6.1.32 R149290

Test Drive the box: https://app.vagrantup.com/Svpernova09/boxes/demo-bento-22.04/versions/20220427
Output Log: https://gist.github.com/svpernova09/cc252569bdc20b1252c7da7cbbf6217a

**Comment by ramereth** [comment]
Any update on getting this merged/deployed? This is holding us back on being able to test Cinc Server builds on the platform.

**Comment by jkugler** [comment]
I built a box for libvirt locally. All worked well. The box, however, was 3.9G. Maybe some investigation needs to be done one what else might be removable.

It is, however, hanging on "==> default: Waiting for SSH to become available..." even though I'm able to ssh directly in to the machine using its IP address as shown in the MOTD output.

**Comment by jkugler** [comment]
If I use this command:
`ssh -i /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/keys/vagrant vagrant@192.168.121.231` I am able to log in to the box, but setting vagrant logging to `debug` I get this over and over in the terminal:
```
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Checking key permissions: /home/jkugler/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 192.168.121.231
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/jkugler/.vagrant.d/insecure_private_key"]
DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>:never, :password=>nil, :port=>22, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :encryption=>["aes256-ctr", "aes192-ctr", "aes128-ctr", "aes256-cbc", "aes192-cbc", "aes128-cbc", "rijndael-cbc@lysator.liu.se", "blowfish-ctr", "blowfish-cbc", "cast128-ctr", "cast128-cbc", "3des-ctr", "3des-cbc", "idea-cbc", "arcfour256", "arcfour128", "arcfour", "none"], :logger=>#<Logger:0x00005604ae88f1b8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00005604ae88eee8 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00005604ae88d020 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x00005604ae89c750>, @binmode=false, @mon_data=#<Monitor:0x00005604ae88cda0>, @mon_data_owner_object_id=68580>>, :keys=>["/home/jkugler/.vagrant.d/insecure_private_key"], :remote_user=>"vagrant"}

DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2022-04-29T13:33:24.448114 #649043] DEBUG -- net.ssh.transport.session[10bf8]: establishing connection to 192.168.121.231:22
D, [2022-04-29T13:33:24.448441 #649043] DEBUG -- net.ssh.transport.session[10bf8]: connection established
I, [2022-04-29T13:33:24.448485 #649043]  INFO -- net.ssh.transport.server_version[10c0c]: negotiating protocol version
D, [2022-04-29T13:33:24.448513 #649043] DEBUG -- net.ssh.transport.server_version[10c0c]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux-gnu'
D, [2022-04-29T13:33:24.459186 #649043] DEBUG -- net.ssh.transport.server_version[10c0c]: remote is `SSH-2.0-OpenSSH_8.9p1 Ubuntu-3'
I, [2022-04-29T13:33:24.459926 #649043]  INFO -- net.ssh.transport.algorithms[10c20]: sending KEXINIT
D, [2022-04-29T13:33:24.460281 #649043] DEBUG -- socket[10c34]: queueing packet nr 0 type 20 len 1324
D, [2022-04-29T13:33:24.460436 #649043] DEBUG -- socket[10c34]: sent 1328 bytes
D, [2022-04-29T13:33:24.460614 #649043] DEBUG -- socket[10c34]: read 1080 bytes
D, [2022-04-29T13:33:24.461436 #649043] DEBUG -- socket[10c34]: received packet nr 0 type 20 len 1076
I, [2022-04-29T13:33:24.461510 #649043]  INFO -- net.ssh.transport.algorithms[10c20]: got KEXINIT from server
I, [2022-04-29T13:33:24.461610 #649043]  INFO -- net.ssh.transport.algorithms[10c20]: negotiating algorithms
D, [2022-04-29T13:33:24.462524 #649043] DEBUG -- net.ssh.transport.algorithms[10c20]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ssh-ed25519
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2022-04-29T13:33:24.462545 #649043] DEBUG -- net.ssh.transport.algorithms[10c20]: exchanging keys
D, [2022-04-29T13:33:24.463220 #649043] DEBUG -- socket[10c34]: queueing packet nr 1 type 30 len 148
D, [2022-04-29T13:33:24.463288 #649043] DEBUG -- socket[10c34]: sent 152 bytes
D, [2022-04-29T13:33:24.466825 #649043] DEBUG -- socket[10c34]: read 312 bytes
D, [2022-04-29T13:33:24.466881 #649043] DEBUG -- socket[10c34]: received packet nr 1 type 31 len 292
D, [2022-04-29T13:33:24.467926 #649043] DEBUG -- socket[10c34]: queueing packet nr 2 type 21 len 20
D, [2022-04-29T13:33:24.468001 #649043] DEBUG -- socket[10c34]: sent 24 bytes
D, [2022-04-29T13:33:24.468274 #649043] DEBUG -- socket[10c34]: received packet nr 2 type 21 len 12
D, [2022-04-29T13:33:24.468532 #649043] DEBUG -- net.ssh.authentication.session[10c48]: beginning authentication of `vagrant'
D, [2022-04-29T13:33:24.468618 #649043] DEBUG -- socket[10c34]: queueing packet nr 3 type 5 len 28
D, [2022-04-29T13:33:24.468655 #649043] DEBUG -- socket[10c34]: sent 96 bytes
D, [2022-04-29T13:33:24.469398 #649043] DEBUG -- socket[10c34]: read 96 bytes
D, [2022-04-29T13:33:24.469462 #649043] DEBUG -- socket[10c34]: received packet nr 3 type 6 len 28
D, [2022-04-29T13:33:24.469509 #649043] DEBUG -- net.ssh.authentication.session[10c48]: trying none
D, [2022-04-29T13:33:24.469687 #649043] DEBUG -- socket[10c34]: queueing packet nr 4 type 50 len 44
D, [2022-04-29T13:33:24.469774 #649043] DEBUG -- socket[10c34]: sent 112 bytes
D, [2022-04-29T13:33:24.476771 #649043] DEBUG -- socket[10c34]: read 112 bytes
D, [2022-04-29T13:33:24.477142 #649043] DEBUG -- socket[10c34]: received packet nr 4 type 51 len 44
D, [2022-04-29T13:33:24.477312 #649043] DEBUG -- net.ssh.authentication.session[10c48]: allowed methods: publickey,password
D, [2022-04-29T13:33:24.477400 #649043] DEBUG -- net.ssh.authentication.methods.none[10c5c]: none failed
D, [2022-04-29T13:33:24.477721 #649043] DEBUG -- net.ssh.authentication.session[10c48]: trying publickey
D, [2022-04-29T13:33:24.478179 #649043] DEBUG -- net.ssh.authentication.agent[10c70]: connecting to ssh-agent
D, [2022-04-29T13:33:24.478320 #649043] DEBUG -- net.ssh.authentication.agent[10c70]: sending agent request 1 len 48
D, [2022-04-29T13:33:24.478499 #649043] DEBUG -- net.ssh.authentication.agent[10c70]: received agent packet 5 len 1
D, [2022-04-29T13:33:24.478548 #649043] DEBUG -- net.ssh.authentication.agent[10c70]: sending agent request 11 len 0
D, [2022-04-29T13:33:24.478615 #649043] DEBUG -- net.ssh.authentication.agent[10c70]: received agent packet 12 len 5
D, [2022-04-29T13:33:24.479191 #649043] DEBUG -- net.ssh.authentication.methods.publickey[10c98]: trying publickey (dd:3b:b8:2e:85:04:06:e9:ab:ff:a8:0a:c0:04:6e:d6)
D, [2022-04-29T13:33:24.479300 #649043] DEBUG -- socket[10c34]: queueing packet nr 5 type 50 len 348
D, [2022-04-29T13:33:24.479353 #649043] DEBUG -- socket[10c34]: sent 416 bytes
D, [2022-04-29T13:33:24.485969 #649043] DEBUG -- socket[10c34]: read 112 bytes
D, [2022-04-29T13:33:24.486095 #649043] DEBUG -- socket[10c34]: received packet nr 5 type 51 len 44
D, [2022-04-29T13:33:24.486287 #649043] DEBUG -- net.ssh.authentication.session[10c48]: allowed methods: publickey,password
E, [2022-04-29T13:33:24.486314 #649043] ERROR -- net.ssh.authentication.session[10c48]: all authorization methods failed (tried none, publickey)

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
```

The auth.log shows this:
```
Apr 29 21:33:51 vagrant sshd[1157]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Apr 29 21:33:51 vagrant sshd[1157]: Connection closed by authenticating user vagrant 192.168.121.1 port 39378 [preauth]
```

I don't know what I'm doing differently than vagrant (using the same ssh private key).

**Comment by ramereth** [comment]
@vkarve-chef when will this image be uploaded to vagrantcloud?

**Comment by matuskosut** [comment]
@ramereth this pull request is done/closed. Hopefully we will get some notification from the team in an open issue here: https://github.com/chef/bento/issues/1405#issuecomment-1125876976

**Comment by vkarve-chef** [comment]
@ramereth we are working on getting access to the vagrantcloud account to allow us to push the image. will keep you posted on the progress here.
cc @ashiqueps

**Pull request merged**
