### PR TITLE
Updated to Fedora 25

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Tested x86_64 and i386 builds on:
- Parallels Desktop for Mac Pro 12.1.1
- VMware Fusion 7.1.3
- VirtualBox 5.1.6

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
I would like to drop `yum` support by default by removing the `dnf-yum` package. I think that should be installed by the ones that need it. Vagrant should work without `yum`.

**Comment by cheeseplus** [comment]
Looks like we're removing DNF from all platforms which I don't think should be the case. Can we do this just for 25+?

**Comment by tas50** [comment]
The reason for adding yum was that chef currently doesn't have a DNF provider for packages. That work is happening now, but without this packages won't install

**Comment by rickard-von-essen** [comment]
> The reason for adding yum was that chef currently doesn't have a DNF provider for packages.

So let's keep it for now. 

> Looks like we're removing DNF from all platforms which I don't think should be the case.

Dnf have been the default since Fedora 22. So it should be possible to remove for all supported versions.

**Comment by rickard-von-essen** [comment]
And I haven't dropped `yum` yet. That requires removing `dnf-yum` from the[kickstart](https://github.com/chef/bento/blob/master/http/fedora-latest/ks.cfg#L31)  file.

**Pull request merged**
