### PR TITLE
FreeBSD faster boot

### PR DESCRIPTION
**Pull request by lwhsu**
## Description
Make FreeBSD boot very slightly faster.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
Just a heads up 11.4 seems to be broken on parallels:

image

**Comment by tas50** [comment]
That's before this PR btw

**Comment by lwhsu** [comment]
> Just a heads up 11.4 seems to be broken on parallels:
Thanks for the notification. I don't have parallel environment myself. I'll ask around.

**Comment by tas50** [comment]
Also for some reason the amd64 boxes just hang forever in DD

```
==> virtualbox-iso: + zfs get -pH avail zroot/ROOT/default
==> virtualbox-iso: + cut -f3
==> virtualbox-iso: + avail=1568768
==> virtualbox-iso: + [ 1568768 -ne 0 ]
==> virtualbox-iso: + sleep 15
==> virtualbox-iso: + zfs get -pH avail zroot/ROOT/default
==> virtualbox-iso: + cut -f3
==> virtualbox-iso: + avail=1568768
==> virtualbox-iso: + [ 1568768 -ne 0 ]
==> virtualbox-iso: + sleep 15
==> virtualbox-iso: + zfs get -pH avail zroot/ROOT/default
==> virtualbox-iso: + cut -f3
==> virtualbox-iso: + avail=1568768
==> virtualbox-iso: + [ 1568768 -ne 0 ]
==> virtualbox-iso: + sleep 15
==> virtualbox-iso: + zfs get -pH avail zroot/ROOT/default
==> virtualbox-iso: + cut -f3
==> virtualbox-iso: + avail=1568768
==> virtualbox-iso: + [ 1568768 -ne 0 ]
==> virtualbox-iso: + sleep 15
```

**Comment by lwhsu** [comment]
> Also for some reason the amd64 boxes just hang forever in DD

Hum it's weird, it didn't happen before I submit the pull request. I've tested few times and also got one while building i386. I suspect there is an issue in `minimize.sh`. I will check it more.

**Comment by lwhsu** [comment]
> > Also for some reason the amd64 boxes just hang forever in DD
> 
> Hum it's weird, it didn't happen before I submit the pull request. I've tested few times and also got one while building i386. I suspect there is an issue in `minimize.sh`. I will check it more.

Hopefully #1293 can fix this.

**Pull request merged**
