### PR TITLE
Add oracle-8.6

### PR DESCRIPTION
**Pull request by tierpod**
Signed-off-by: Pavel Podkorytov <pod.pavel@gmail.com>

Add oracle-8.6 box

## Description
Oracle Linux 8.6 was released a while ago (OracleLinux-R8-U6-x86_64-dvd.iso), so it would be nice to have vagrant box for it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass. (I built virtualbox-iso box locally and it works fine)
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tierpod** [comment]
Unfortunately, mirror https://mirror.netcologne.de/oracle-linux don't have OracleLinux-R8-U6-x86_64-dvd.iso file (actually, I checked some others mirrors and they don't have too), so I tested this build in 2 cases:

* official yum.oracle.com: `packer build -var 'mirror=https://yum.oracle.com/ISOS/OracleLinux' -only=virtualbox-iso oracle-8.6-x86_64.json`
* local iso file: `packer build -var 'mirror=file:///path/to/iso' -var 'mirror_directory=' -only=virtualbox-iso oracle-8.6-x86_64.json`

**Review by Stromweld — CHANGES_REQUESTED** [review]
Can you simply change the oracle-8.5-x84_64.json to 8.6 and update the references to 8.5 to 8.6 in that file please? This is the normal behaviour we have been doing is to support just the latest feature release in each major version.

**Comment by tierpod** [comment]
Ok, done. Also, I changed mirror url to official yum.oracle.com, because previous mirror still has no ol 8.6 iso.

**Review by Stromweld — APPROVED** [review]
Testing locally on my workstation passed.

**Pull request merged**
