### PR TITLE
Using more reliable debian mirror

### PR DESCRIPTION
**Pull request by cheeseplus**
Signed-off-by: Seth Thomas <sthomas@chef.io>

### CODE REVIEW

**Comment by rmoriz** [comment]
aren't they exactly the same? Do you have issues with SRV DNS records in VMWare Fusion?

**Comment by cheeseplus** [comment]
My understanding is that they are different but regardless the failures were for virtualbox builders as well and changing the mirror is what did the trick.

**Comment by rmoriz** [comment]
`httpredir.debian.org has been discontinued because of lack of maintenance and now redirects to http://deb.debian.org `

https://wiki.debian.org/DebianGeoMirror

**Comment by cheeseplus** [comment]
While that is definitely true, it still fixed the build so ¯\_(ツ)_/¯

**Pull request merged**
