### PR TITLE
Update Ubuntu 20.04 to 20.04.4

### PR DESCRIPTION
**Pull request by svpernova09**
Signed-off-by: Joe Ferguson <joe@joeferguson.me>

Updated Ubuntu 20.04.3 versions to 20.04.4.

## Description
Latest Ubuntu LTS rollup. 
amd64 updated from http://releases.ubuntu.com/20.04/ [sha](http://releases.ubuntu.com/20.04/SHA256SUMS)

arm64 updated from http://cdimage.ubuntu.com/releases/20.04/release [sha](http://cdimage.ubuntu.com/releases/20.04/release/SHA256SUMS)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by svpernova09** [comment]
Test build:  `packer build --only=parallels-iso ubuntu-20.04-amd64.json:`

Packer version: 1.7.10
Parallels Pro 17.1.1 (51537)
macOS 12.2.1

https://gist.github.com/svpernova09/40574f464139ccbd452b596bbd5188a2

**Comment by WolfangAukang** [comment]
Hi, I have been trying this (specifically the Ubuntu 20.04 Live template) on Virtualbox, but the OS setup part gets stuck and asks to press for any key to start a live shell, as shown below:

image

**Comment by leegarrett** [comment]
Hi, please merge this PR. I can confirm that it indeed correctly builds the current Ubuntu 20.04.4 release. The error reported by @WolfangAukang is likely related to a flaky internet uplink that will happen on the current code, too, so this is not a regression.

**Review by sanjain-progress — APPROVED** [review]

**Review by kasif-adnan — APPROVED** [review]

**Comment by Mte90** [comment]
a new release to vagrant boxes was uploaded with this fix?

**Comment by ashiqueps** [comment]
Hey @Mte90,

A new build has been released to vagrant cloud with this fix!

**Pull request merged**
