### PR TITLE
Add Ubuntu 15.04 vivid velvet

### PR DESCRIPTION
**Pull request by vincentaubert**
This PR adds Ubuntu 15.04 to bento

### CODE REVIEW

**Comment by vincentaubert** [comment]
Link tout issue #345

**Comment by kramvan1** [comment]
:+1:

**Comment by jjasghar** [comment]
:+1:

**Comment by fnichol** [comment]
We still have a tiny bit of work to do with this PR. I believe I have a fix, and if so will tack it on.

packer-ubuntu-15 04-amd64 2015-04-28 17-26-46

**Comment by fnichol** [comment]
There is currently an issue getting the VMware Tools to properly compile against the version of the kernel. Dropping this here for future reference as I continue to diagnose:

https://communities.vmware.com/thread/509231

**Comment by rickard-von-essen** [comment]
I tested it on all three builders, **vmware-iso** fails with the same error as in the above screenshot. 

**parallels-iso** and **virtualbox-iso** succeeds but with some strange errors printed regarding not finding /dev/sda2. The boxes seems to work fine and I'm trying to get hold of the error from a log file.

**Comment by fnichol** [comment]
@rickard-von-essen thanks for the confirmation!

I can get the builds to complete by adding the following to the preseed:

```
d-i grub-installer/bootdev string /dev/sda
```

At the moment, I'm tracking down the VMware Tools install failures and confirming that Parallels and VirtualBox versions are working.

**Comment by vincentaubert** [comment]
preseed updated

**Comment by rickard-von-essen** [comment]
This is the error I get during install with **parallels** and **virtualbox**.
screen shot 2015-04-30 at 09 17 32
It doesn't stop the installation and everything seems fine in the vagrant box.
The error persists even after apply the grub patch:
```
d-i grub-installer/bootdev string /dev/sda
```

**Comment by YpNo** [comment]
Try to use 
d-i grub-installer/bootdev string default
instead of define a disk partition. Allow to automatic select the first device available.

**Comment by rickard-von-essen** [comment]
@YpNo 
> d-i grub-installer/bootdev string default

Fails on all builders with _Unable to install GRUB in default_

**Comment by fnichol** [comment]
Relevant blocking issue for Parallels Tools installation:
https://forum.parallels.com/threads/parallels-tools-installation-problem-on-ubuntu-15-04.328218/

**Comment by jklare** [comment]
@fnichol parallels forum says blocking issue should be fixed

**Comment by fnichol** [comment]
@jklare Right you are, I was just going to update this thread

**Comment by fnichol** [comment]
Given that VMware Fusion 7.1.2 was released last week, I'm seeing if this clears our blocker. Fingers crossed…

**Comment by tas50** [comment]
With the blocker resolved can this get merged?  There's a lot of community cookbooks that need to get tested with systemd on 15.04.  This would really help that out.

**Comment by jjasghar** [comment]
:+1:

**Pull request closed without merging**
