### PR TITLE
squashed commit to add all the qemu options on all the systems.

### PR DESCRIPTION
**Pull request by dmlb2000**
This adds the qemu options for all systems. Should be "squashed" I didn't use the git features for this I just did a diff and committed it, it was easier to inspect the diff that way.

### CODE REVIEW

**Comment by mattiasgiese** [comment]
With the AutoYaST fixes from #373 qemu build works flawlessly for SLES 11.3 (i386/x86_64) and SLES12. :+1:

**Comment by dmlb2000** [comment]
@mattiasgiese  #373 Should also allow the qemu specific disk_interface option to opensuse to be removed like it is for sles since they are related distributions correct?

**Comment by mattiasgiese** [comment]
Yep, starting with SLES 11 SP2 and openSUSE 12 YaST will take the first device found if no specific one is given in the bootloader/partitioning section.

**Comment by mattiasgiese** [comment]
I will go ahead and create a PR for openSUSE.

**Comment by johnbellone** [comment]
:+1:

**Comment by cheeseplus** [comment]
@dmlb2000 could you rebase this one? We had a bunch of other commits related to the other builders that took priority but I don't see any reason why we can't add QEMU builders.

**Comment by dmlb2000** [comment]
Looks like there's a lot of changes I'll take a bit to make a new diff...

**Comment by cheeseplus** [comment]
Sorry about that it was more about fixing up things that were broken then adding new features but just wanted folks to know I hadn't forgotten.

**Comment by dmlb2000** [comment]
Hmmm, I recreated the branch to resquash the commit... I'll open a new pull request.

**Pull request closed without merging**
