### PR TITLE
Add support for Ubuntu 20.04

### LINKED ISSUE #1281: Add support for Ubuntu 20.04 LTS Boxes
### Describe the Enhancement:
https://app.vagrantup.com/bento/boxes/ubuntu-20.04 would be available as a basebox with the recently released Ubuntu 20.04 LTS version

### Describe the Need:
This would probably be beneficial for any user of the existing bento/ubuntu boxes, as the newly released 20.04 version is an LTS version. Also availability of vmware_desktop and parallels boxes in addition to virtualbox is a big plus for the bento boxes.

### Current Alternative
I found no other reliable / trusted basebox for Ubuntu 20.04 so far. The "official" ubuntu baseboxes are virtualbox only, thus they won't help users who need vmware_desktop or parallels boxes

### Can We Help You Implement This?:
Unfortunately I don't have the time and resources available to implement it myself right now, as it seems a bit more complicated than just updating the iso URL and checksums :-/ The issue is that with Ubuntu 20.04 the classic .iso images with the "d-i" / preseed installer are no longer available, there is only the new "subiquity" live installer. I guess this requires quite a bit more effort to adapt on packer side, if even possible at all. That's why I'm asking for your help here, as you are certainly have much more expertise in this than I do...

### PR DESCRIPTION
**Pull request by svpernova09**
Adds new Template for Ubuntu 20.04
## Description

New template for new Ubuntu LTS
## Related Issue
Resolves #1281

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by svpernova09** [comment]
Here's a gist of the build log of this template + Virtualbox 6.0.0: https://gist.github.com/svpernova09/25ed05b0763d033b78466a228149b29a

**Comment by svpernova09** [comment]
To test drive the box: https://app.vagrantup.com/Svpernova09/boxes/ubuntu-20.04-amd64

**Comment by tas50** [comment]
Thanks @svpernova09. If someone wants to later get this updated to the new method of autoinstalling I'd love that, but this will get us a box for now.

**Comment by svpernova09** [comment]
100% I'd love to see how the new installer would be utilized with Packer.

**Comment by noaho** [comment]
Just came to say thankyou! 😊

**Comment by tknerr** [comment]
Awesome, thanks @svpernova09 @tas50 !

**Pull request merged**
