### PR TITLE
Add debian 9 ppc64el qemu/libvirt builder definition

### PR DESCRIPTION
**Pull request by justinlynn**
### Description

This change adds a Debian 9.6 definition for qemu/kvm -> libvirt builds on PowerPC64 Little Endian hardware. Change prompted by the release of the [Raptor Computing Systems Talos 2](https://raptorcs.com), a fully open source/documented IBM POWER9 OpenPOWER workstation.

In particular the ppc64le build has a different menu and boot system command set which makes it incompatible with x86.

### Issues Resolved

* Adds architecture support

### CODE REVIEW

**Comment by cheeseplus** [comment]
While this is probably clear to merge, it would be unlikely that we'd build and host images in Vagrant Cloud given the difficulty in setting up builders and the niche-ness of the platform.

**Comment by justinlynn** [comment]
Understood and agreed as to nicheness of platform. I'm hoping to add support for the other listed distros and provide build infrastructure for users of the architecture/platform but certainly don't expect Vagrant Cloud to support the infrastructure. Perhaps the core team would prefer that this architecture be supported in a fork maintained by myself?

**Comment by cheeseplus** [comment]
We're happy to store the definitions in these cases - we've got plenty of templates that we don't build and host. I just want to make sure contributors are aware and you seem to be 👍 already.

**Comment by justinlynn** [comment]
Cheers mate :+1:

**Pull request merged**
