### PR TITLE
Adding a package for Centos 8

### PR DESCRIPTION
**Pull request by SMillerDev**
## Description
Adding a package for Centos 8 to be able to use test-kitchen with the new release. This commit was made from the github web UI so most of the checklist can't be done.

## Related Issue
None

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@SMillerDev This will need to be signed off for the DCO and it also looks like your floppy file is missing accounting to the packer validation build failure.

**Comment by SMillerDev** [comment]
I have no idea what the second part of that means. I just copied what I thought was needed.

**Comment by tas50** [comment]
It's referencing a disk that doesn't exist, but I can clean that up probably

**Comment by tas50** [comment]
Scratch that it was just packer validation being upset about relative paths

**Comment by SMillerDev** [comment]
Thanks @tas50

**Pull request merged**
