### PR TITLE
Amazon Linux 2

### PR DESCRIPTION
**Pull request by johnjelinek**
### Description

Pushes forward on the Amazon Linux 2 box.

### Issues Resolved

Continues where https://github.com/chef/bento/pull/1144 left off.

### CODE REVIEW

**Comment by Fashaun** [comment]
Does it support vmware?

**Comment by johnjelinek** [comment]
Kinda. I wrote this for the purpose of VMware, but I didn't add that part to this codebase. Part of the challenge with my VMware was seeding cloudinit with the right values to set up the interface after the template is made.

**Comment by Fashaun** [comment]
Could you share your code base?

**Comment by johnjelinek** [comment]
Unfortunately, I don't work for that company anymore, so I don't have it available.

**Pull request merged**
