### PR TITLE
Update Windows Nano for RTM

### PR DESCRIPTION
**Pull request by tas50**
Also add 2016 to the name since I assume we'll see a Server 2019? Nano sometime

Signed-off-by: Tim Smith tsmith@chef.io

### CODE REVIEW

**Comment by mwrock** [comment]
See:
https://github.com/mwrock/packer-templates/blob/master/vbox-nano.json
and
https://github.com/mwrock/packer-templates/blob/master/vbox-2016.json

**Comment by mwrock** [comment]
not at all @tas50

**Comment by cheeseplus** [comment]
@tas50 is this ready to go or should I wait for a superseding PR?

**Comment by tas50** [comment]
Very much not ready. I forgot all about this PR

**Comment by tas50** [comment]
Leaving this branch, but killing this PE. It needs a lot of work

**Pull request closed without merging**
