### PR TITLE
Remove Fedora 33 and add Fedora 35

### PR DESCRIPTION
**Pull request by jstaph**
## Description

remove the Fedora 33 build template and target, and add Fedora 35.  Pretty straight forward change to keep pace with the upstream distro

## Related Issue

N/A

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
    > I've built and tested the box (successfully) locally
- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tas50** [comment]
@jstaph Can you sign this off for the DCO so we can merge it?

**Comment by jstaph** [comment]
Absolutely, and apologies; I wasn't familiar with the DCO (and feel like I should be, I've been around long enough).  While I was at it, I added (tested and working) an update script for Fedora 35 as well.

**Comment by jstaph** [comment]
@tas50 Is there anything else I can do to help on this?

**Comment by myii** [comment]
Tested out a [Bento-fork Vagrant box for Fedora 35](https://app.vagrantup.com/garyburgmann/boxes/fedora-35), which is near identical to this PR, except for the additional `packer_templates/fedora/scripts/update.sh` -- working well for us.  It would be great to have this available as a standard Bento box before we start using it for more of our repos.

**Comment by jstaph** [comment]
@tas50 ping; is there anything else I can do with this one?  Thanks!

**Comment by tas50** [comment]
Sorry I'm not at Chef anymore so I don't have privs on this repo

**Comment by jstaph** [comment]
> Sorry I'm not at Chef anymore so I don't have privs on this repo

I'm very sorry to hear that.  Definitely Chef's loss.  Here's hoping you're enjoying whatever turned out to be next!

**Review by kasif-adnan — APPROVED** [review]

**Review by ashiqueps — APPROVED** [review]

**Review by sanjain-progress — APPROVED** [review]

**Review by kasif-adnan — APPROVED** [review]

**Pull request merged**
