### PR TITLE
Added support for Fedora 27

### PR DESCRIPTION
**Pull request by Defilan**
Signed-off-by: Christopher P. Maher <defilan@gmail.com>

This adds a Packer template for Fedora 27. This has been tested and run with Virtualbox.

### CODE REVIEW

**Comment by tas50** [comment]
From what I read this is going to be workstation since they haven't shipped server yet. We should probably hold off until they ship the new component based server ISO

**Comment by Defilan** [comment]
Ah ok, that makes sense. I agree, let's wait until the iso comes out. Doesn't look like it will be too long. Thanks for catching that.

**Comment by rickard-von-essen** [comment]
Fedora 27 Server seems to be available now.

**Comment by Defilan** [comment]
@rickard-von-essen Awesome, I'll update the code and test it. If it looks good, I'll push it up for review this afternoon. Thanks for the heads up :)

**Comment by alindeman** [comment]
:tada:

**Comment by tas50** [comment]
@Defilan I think your rebase went wrong here.

**Comment by Defilan** [comment]
@tas50 Yeah, you're right. Don't know what the heck I did this time, haha. I'll go ahead and resubmit this evening. Should be GTG later tonight.

**Pull request closed without merging**
