### PR TITLE
Scientific Linux packer built vagrant box 

### PR DESCRIPTION
**Pull request by githubfoam**
(seperate PR) 
https://www.scientificlinux.org/

### CODE REVIEW

**Comment by cheeseplus** [comment]
I'm ok with provisionally adding this one but we really should include the other providers (vmware, parallels) if possible. In 6 months we'll check the download counts to see if folks are actively using it - curious if it gets any traction.

**Comment by githubfoam** [comment]
I d like to do that.Problem is I do not know how to test vmware and
parallel? I am windows10/ubuntu on my desktops.Is it possible to test
builds on those hosts? Thnx.

**Comment by rickard-von-essen** [comment]
As long as they VM tools works on Parallels/VMware with CentOS this should just work.

**Comment by githubfoam** [comment]
I do not have licensed parallels or vmware on my laptop.I have windows10 on
my laptop.

**Comment by cheeseplus** [comment]
We can build them, you don't necessarily have to test all of them locally. It's reasonable to assume a base of Vbox, Fusion, and Parallels - other providers like qemu and Hyper-V are added on an "as works" basis.

**Comment by githubfoam** [comment]
how do you do that? is it linked to travis on gitlab? kind of pipeline
running on gitlab with packer builds?

**Comment by cheeseplus** [comment]
It's a pipeline that I maintain and is not publicly visible. I'll be pushing these builds as soon as I can get them working on the hardware.

**Pull request merged**
